### PR TITLE
Updated .gitignore

### PR DESCRIPTION
**Pull request by BondarenkoArtur**

### CODE REVIEW

**Comment by pavart** [comment]
I see a lot of junk in .gitignore which is not related to typical C++ project.
For example python, eclipse, and so on.
Maybe it's a good chance to remove all this crap?
@Badrpas @BondarenkoArtur

**Comment by BondarenkoArtur** [comment]
> I see a lot of junk in .gitignore which is not related to typical C++ project.  

Agreed, but I don't know is there something that needed by VS.

**Comment by pavart** [comment]
Let for now remove the following parts:
```
## Eclipse
# External tool builders
# Locally stored "Eclipse launch configurations"
# CDT-specific
# PDT-specific
# SQL Server files
## Python
# Packages
# Installer logs
# Unit test / coverage reports
#Translations
#Mr Developer

```
WDYT?

**Comment by BondarenkoArtur** [comment]
> WDYT?

Agreed, removed them

**Comment by BondarenkoArtur** [comment]
@Badrpas merge this if you agreed

**Pull request merged**
